/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import componentAdmin.Card;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.ImageIcon;

/**
 *
 * @author sasimai
 */
public class CartoonScrollPaneUser extends javax.swing.JPanel {

    /**
     * Creates new form CartoonScrollPaneUser
     */
    public CartoonScrollPaneUser() {
        initComponents();
        CardMain []cat = {new CardMain(), new CardMain(), new CardMain(), 
            new CardMain(), new CardMain(), new CardMain(), new CardMain(), new CardMain(), new CardMain(), 
            new CardMain(), new CardMain(), new CardMain(), new CardMain(), new CardMain()};
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(15, 15, 15, 15);
        int x = 0;
        int y = 0;
        ImageIcon imgThisImg = new ImageIcon("./src/images/Do.png");
        imgThisImg.setImage(imgThisImg.getImage().getScaledInstance(200,275,Image.SCALE_DEFAULT));
//        String cate[] = {"Romance", "Action", "Drama", "Fiction", "Comedy"};
        for (int i = 0; i < cat.length; i++) {
            gbc.gridx = x;
            gbc.gridy = y;
            jPanel1.add(cat[i], gbc);
//            cat[i].getjLabel1().setIcon(imgThisImg);
            cat[i].getjLabel1().setText("test");
            x++;
            if (x == 4) {
                x = 0;
                y++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jPanel1 = new javax.swing.JPanel();

        scrollPane1.setSize(new java.awt.Dimension(951, 602));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        scrollPane1.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
